import pyautogui as may
# may.mouseInfo()
may.press ('win')
may.write ('instagram',interval=0.5)
may.press ('enter')
may.sleep(3)
may.moveTo (229,371)
may.click ()
may.sleep(3)
may.press ('Tab')
may.sleep (2)
may.write ()
may.press ('Tab')
may.write ()
may.sleep (2)
may.press ('enter')
