import pyautogui as neni
# neni.mouseInfo()
neni.alert(text='vamos começar?', title='caixa de mensagem', button='OK')
neni.press('win')
neni.write('github',interval=0.5)
neni.press('enter')
neni.sleep(2)
neni.moveTo (255,385)
neni.click()
neni.sleep(2)
neni.moveTo (871,129)
neni.click ()
neni.sleep (3)
neni.write ('Miriisa', interval=0.5)
neni.press('TAB')
neni.sleep (2)
neni.write ()
neni.press ('enter')

